### ISSUE TITLE
Plasma wayland documentation

### ISSUE THREAD

**Issue by jamesbt365** [OpenTabletDriver/OpenTabletDriver.Web#61] opened 2022-02-20 13:43 UTC
This should be documented due to the weird way that plasma wayland handles the tablet. 

Refer [here](https://github.com/OpenTabletDriver/OpenTabletDriver/issues/2083)

**Comment by InfinityGhost** [comment] 2022-03-07 00:27
Duplicate of #43

**Closed by InfinityGhost** 2022-03-07 00:27 UTC
